config/routes.rb
Rails.application.routes.draw do
  get('/', to: 'welcome#index', as: :home )

  resources :ideas do
    resources :reviews
    resources :likes, only: [:create, :destroy]
    resources :joins, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


      can :manage, Idea do |idea|
        user == idea.user
      end

      can :manage, Review do |review|
        user == review.user
      end


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :joins, dependent: :destroy
  has_many :users, through: :joins

  validates :title, presence: {message: "must be given"}, uniqueness: true
  validates :description, presence: true, length: {minimum: 5, maximum: 1000}

  def like_for(user)
    self.likes.find_by_user_id(user)
  end

  def liked_by?(user)
    likes.find_by_user_id(user.id).present?
  end

  def join_for(user)
    self.joins.find_by_user_id(user)
  end

  def joined_by?(user)
    joins.find_by_user_id(user.id).present?
  end


  before_save :squeeze

  private

  def squeeze
    self.title.squeeze!(' ')
  end

end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :idea_id, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :idea_id, uniqueness: {scope: :user_id}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user


  validates :body, presence: true, length: {minimum: 5, maximum: 1000}

end

app/models/user.rb
class User < ApplicationRecord

  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify
  has_many :likes, dependent: :destroy
  has_many :ideas, through: :likes, source: :idea
  has_many :joins, dependent: :destroy
  has_many :ideas, through: :joins, source: :idea

  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :first_name, :last_name, presence: true


 def full_name
   "#{first_name} #{last_name}"
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  helper_method :user_signed_in?


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_session_path, alert: 'You must sign in or sign up first!'
    end
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to idea_path(@idea)

    else
      render :new
    end
  end

  def index
    @idea = Idea.new
    @ideas = Idea.all.order(created_at: :desc)
  end

  def show
    @review = Review.new
    # @reviews = @idea.reviews.order(created_at: :desc) #mine
    @reviews = @idea.reviews.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @idea.update(idea_params)
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end

private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def authorize_user!
    unless can?(:manage, @idea)
      flash[:alert] = 'Access Denied!'
      redirect_to home_path
    end
  end


end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  before_action :authenticate_user!

  def create
    @join = Join.new
    @idea = Idea.find params[:idea_id]
    @join.idea = @idea
    @join.user = current_user
    if @join.save
      redirect_to ideas_path
    else
      redirect_to idea_path(@idea)
    end
  end

  def destroy
    @idea = Idea.find params[:idea_id]
    @join = current_user.joins.find params[:id]
    @join.destroy
    redirect_to ideas_path
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = Like.new
    @idea = Idea.find params[:idea_id]
    @like.idea = @idea
    @like.user = current_user
    if @like.save
      redirect_to ideas_path
    else
      redirect_to idea_path(@idea)
    end
  end

  def destroy
    @idea = Idea.find params[:idea_id]
    @like = current_user.likes.find params[:id]
    @like.destroy
    redirect_to ideas_path
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_idea
    before_action :find_review, only: [:destroy]
    before_action :authorize_user!, only: [:destroy]

  def create
    @review = Review.new(review_params)
    @review.idea = @idea
    @review.user = current_user
    if @review.save
      redirect_to idea_path(@idea)
    else
      @reviews = @idea.reviews.order(created_at: :desc)
      render 'ideas/show'
    end
  end

  def destroy
    @review.destroy
    redirect_to idea_path(@idea)
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end

  def find_idea
    @idea = Idea.find params[:idea_id]
  end

  def find_review
    @review = Review.find params[:id]
  end

  def authorize_user!
    unless can?(:manage, @review)
      flash[:alert] = "Access Denied!"
      redirect_to home_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Thank you for sign in!'
      redirect_to home_path
    else
      flash.now[:alert] = 'Wrong email or password!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Signed Out! See ya!!'
  end


private
  def session_params
    params.require(:session).permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new # sign up page
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id 
        flash[:notice] = "Thank you for signing up, #{@user.first_name}!"
        redirect_to home_path
      else
        render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation
      )
    end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, html: {class: "form-group"} do |form| %>
  <% if @idea.errors.present? %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
       <%= @idea.errors.full_messages.join(', ') %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="input-group mb-1">
      <%= form.label :idea, class: "input-group-addon", style: "width:100px;" %>
      <%= form.text_field :title, class: "form-control", required: "required" %>
  </div>

  <div class="input-group mb-1">
    <%= form.label :description, class: "input-group-addon", style: "width:100px;" %>
    <%= form.text_area :description, class: "form-control", rows: "6", required: "required" %>
  </div>


  <%= form.submit "Submit", class:"btn btn-secondary btn-sm" %>


<% end %>

app/views/ideas/edit.html.erb
<div class="container mt-3">
  <h4>Update this idea</h4>
  <%= render 'form' %>
</div>

app/views/ideas/index.html.erb
<div class="container mt-3">
  <h3>Great Ideas</h3>

<%# Only signed-in users can see this new form button -----------------------%>
<% if user_signed_in? %>

  <div class="text-right">
    <button type="button" class="btn btn-outline-secondary btn-sm mb-3" data-toggle="modal" data-target=".bd-example-modal-lg">New Question</button>
  </div>

<%# add ` data-backdrop="static" data-keyboard="false" ` to prevent from clicking
on area outside of the pop-up, the pop-up fades out %>
      <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg">
          <div class="modal-content pr-3 pt-3">
            <p class"text-right">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </p>
            <div class="container p-3">

              <h5>New Idea</h5>
                <%= render 'form' %>
            </div>

          </div>
        </div>
      </div>
<% end %>
<%#-----------------------------------------------------------------------%>
  <div class="frame">

    <% @ideas.each do |idea| %>
      <div class="card">
        <div class="card-header">
          <i class="fa fa-plus-circle"></i>
          <i class="fa fa-minus-circle hide"></i>
          <%= link_to idea.title, idea_path(idea), class: "linkStyle" %>
        </div>
        <div class="card-body hide">
          <p class="card-text"> <%= idea.description %> </p>
            <i class="fa fa-user-o"></i><small>  <%= idea.user.full_name %></small>


            <% if user_signed_in? && idea.joined_by?(current_user) %>
              <%= link_to "Not Join", idea_join_path(idea, idea.join_for(current_user)), class: "btn btn-outline-dark btn-sm", method: :delete %>
            <% else %>
              <%= link_to "Join", idea_joins_path(idea), class: "btn btn-outline-warning btn-sm", method: :post   %>
            <% end %>

            <% if user_signed_in? && idea.liked_by?(current_user) %>
              <%= link_to "Dislike", idea_like_path(idea, idea.like_for(current_user)), class: "btn btn-outline-dark btn-sm", method: :delete %>
            <% else %>
              <%= link_to "Like", idea_likes_path(idea), class: "btn btn-outline-danger btn-sm", method: :post   %>
            <% end %>

            <small class="float-right">
              <i class="fa fa-address-book text-info"></i>
              <%= idea.joins.count %>
              &nbsp&nbsp&nbsp&nbsp&nbsp
              <i class="fa fa-heart text-danger"></i>
              <%= idea.likes.count %></small>



        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/ideas/new.html.erb
<div class="container mt-3">
  <h4>New Idea</h4>
  <%= render 'form' %>
</div>

app/views/ideas/show.html.erb
<div class="container mt-3">

  <div class="card mt-2 mb-5 border border-dark">
    <div class="card-header font-weight-bold">
      <h5 class="card-title"><%= @idea.title%></h5>
      <h6 class="card-subtitle mb-2 text-muted"><small>
        updated: <%= time_ago_in_words(@idea.updated_at) %> ago
      </small></h6>
    </div>
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted text-right">By:
        <%= @idea.user&.full_name || "[deleted]" %>
      </h6>
      <p class="card-text"><%= @idea.description %></p>

      <% if can?(:manage, @idea) %>

          <%= link_to(
               'Edit',
               edit_idea_path(@idea),
               class: "btn btn-outline-secondary btn-sm"
               )
           %>
          <%= link_to(
               'Delete',
               idea_path(@idea),
               class: "btn btn-outline-secondary btn-sm",
               method: :delete,
               data: {confirm: 'Are you sure what you are doing now ???'}
             )
          %>
      <% end %>
    </div>
  </div>

<%#------------------------------------------------------------------------%>

  <%= form_for [@idea, @review] do |f| %>
    <div class="form-group p-3 rounded" style="background-color: #b0aac2;">
      <h5>Write a review:</h5>
      <% if @review.errors.present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= @review.errors.full_messages.join(', ') %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <div class="form-group row p-2">
        <%= f.label :review, class: "text-right col-sm-2" %>
        <%= f.text_area :body, class: "col-sm-10 form-control" %>

      </div>
      <%= f.submit "Submit Review", class: "btn btn-outline-light btn-sm mt-2" %>
    </div>
  <% end %>
<%#------------------------------------------------------------------------%>
  <% @reviews.each do |review| %>
     <div class="card my-2 border border-dark">
           <div class="card-body">
            <p><strong>Reviews:</strong> <%= review.body %></p>
            <p class="text-right">
              <i class="fa fa-user-o"></i><em>  <%= review.user.full_name %></em></p>
            <p class="text-right"><small>Created At: <%= time_ago_in_words(review.created_at) %> ago</small></p>

            <p>
              <% if can?(:destroy, review)%>
                <%= link_to(
                  'Delete',
                  idea_review_path(@idea, review),
                  data: {confirm: 'Are you sure?'},
                  class: "btn btn-outline-danger btn-sm",
                  method: :delete
                ) %>
              <% end %>
            </p>
          </div>
      </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreatIdea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">IdeaFactory</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'New Idea', new_idea_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'All Ideas', ideas_path, class:"nav-link" %>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0">
        </form>
        <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#"><%= current_user.first_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to(
              'Sign Out',
              session_path,
              method: :delete,
              class:"nav-link",
              data: {confirm: 'Do you really want to sign out?'}
            ) %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      </div>
    </nav>


    <div class="container">
       <% if flash[:notice].present? %>
         <div class="alert alert-success alert-dismissible fade show" role="alert">
           <%= flash[:notice] %>
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
       <% elsif flash[:alert].present? %>
         <div class="alert alert-danger alert-dismissible fade show" role="alert">
           <%= flash[:alert] %>
           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span>
           </button>
         </div>
       <% end %>

     </div>
    <%= yield %>


  </body>
</html>

app/views/users/new.html.erb
<div class="container mt-3">


  <%= form_for @user do |f| %>
    <% if @user.errors.present? %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= @user.errors.full_messages.join(', ') %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <div>
      <%= f.text_field :first_name,
        class: "form-control mb-1",
        placeholder: "First Name"%>
    </div>
    <div>
      <%= f.text_field :last_name,
        class: "form-control mb-1",
        placeholder: "Last Name" %>
    </div>
    <div>
      <%= f.email_field :email,
        class: "form-control mb-1",
        placeholder: "Email" %>
    </div>
    <div>
      <%= f.password_field :password,
        class: "form-control mb-1",
        placeholder: "Password" %>
    </div>
    <div>
      <%= f.password_field :password_confirmation,
        class: "form-control mb-1",
        placeholder: "Password Confirmation" %>
    </div>
    <%= f.submit 'Sign Up', class: "btn btn-primary btn-sm" %>
  <% end %>

</div>

app/views/welcome/index.html.erb
<div class="bg-01">
  <div class="container-fluid pt-3 text-right">

      <h3 class="display-3">Idea Factory</h3>

  </div>
</div>